FROM rust:alpine3.15 as builder

RUN apk add --no-cache musl-dev
WORKDIR /usr/bin/app
COPY . .
RUN cargo build --release --bin client

FROM debian:buster-slim as runner
RUN apt-get update && \
    apt-get install -y dumb-init && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/

ARG _PORT=7777

COPY --from=builder /usr/bin/app/target/release/client /usr/local/bin
RUN chmod +x /usr/local/bin

ENV RUST_LOG="info"
ENV PORT=$_PORT

ENTRYPOINT ["dumb-init"]
CMD ["client"]
